### ISSUE TITLE
cannot load an 3E+ cart

### ISSUE THREAD

**Issue by retrac0** [JetSetIlly/Gopher2600#14]
Hey!  Great emulator, and wonderful, clear code.  (I poked into the mapper code to see if I could hunt down this bug.)

Stella accepts these 3E+ cart demos I was working on, which run and display a rather ugly X/O pattern.  

The first game-9k.e3p loads in debug mode until you try to run it, but is then rejected in run mode probably due to its 9 KB size: 

    * error in RUN mode: playmode: setup: cartridge: 3E: wrong number of bytes in the cartridge data

The second game-8k.e3p is the same code.  Just shrunk down to 8 KB (a normal power of 2).  It loads in RUN mode, and then does nothing and seems to freeze the emulator entirely.  But when in DEBUG mode it prints this and quits:

    * error in DEBUG mode: debugger: disassembly: bless: cartridge does not reset to an address in the cartridge area.

I use banks-witching very aggressively, which may be why?  I'm not sure Stella should accept it either, honestly... but it does run in Stella.

Attached is a zip file with the two ROM images.

[game.zip](https://github.com/JetSetIlly/Gopher2600/files/6729826/game.zip)

**Comment by JetSetIlly** [comment]
Thanks for the bug report and thanks for the comments! Clear code was one of my goals when starting the project so I'm pleased someone agrees. 

As you say, the 9k cartridge won't load because of the size. I'll look into fixing that by cropping the filesize to 4k boundaries (with a special compensation for 2k files)

The 8k cartridge meanwhile. is triggering a couple of bugs. The first is that the automatic fingerprinting isn't detecting that it's a 3e+. It actually thinks it's a 3e. You can force the use of a particular mapping through either a command line argument or through the file extension. In the case of 3e+ the command line would be something like:

gopher2600 -mapping 3e+ game-8k.e3p

Or you can change the file extension to game-8k.3e+

To be honest, I'm intrigued by the existing extension of e3p. Is that something you've seen before? I'll add it to the list of options if so.

The mapping/file-extension option also works for the debugger of course but there's an additional problem during disassembly. I'll need to track the problem down exactly but for now we can turn the error into a log entry.

In debugger.go

	err = dbg.Disasm.FromMemory()
	if err != nil {
		logger.Log("debug", err.Error())
		// return err
	}


I won't push that change just yet. I'll bundle it with the other changes, later today hopefully.

   1. Correct fingerprinting of 3e+
   2. Loading of files that are not exactly divisible by 4k
   3. Investigate and fix disassembly of 3e+ cartridges
   4. Log disassembly failure rather than program exit. Maybe indicate in the disasm window
       that something's gone wrong.


Nice effect BTW :-)

![crt_game-8k_20210629_094611_double_2](https://user-images.githubusercontent.com/58750902/123767698-9419bd00-d8bf-11eb-9f59-e2a29bbe7335.jpg)

**Comment by retrac0** [comment]
> To be honest, I'm intrigued by the existing extension of e3p. Is that something you've seen before?

It's one of the extensions Stella accepts for the format (along with e3+ ...which is apparently more widely supported :))

> From what I have learned about 3e+ in the past, it requires a byte sequence of TJ3E somewhere in the ROM. 

3E+ is just a handful of homebrew developers over the last couple years.  The fuss is from it being practical to implement in an actual cartridge without fancy FPGAs or such, while being flexible enough to handle complicated things (like the virtual framebuffer in my demo).  

So, it's very possible we're all targeting slightly different ideas of the specification.  I think it's still being defined somewhat, in practice.  I hadn't heard of the TJ3E fingerprint, I'll look into that.

9 KB ROM is of course unusual.  In practice any physical 3E+ cartridge would probably be a power of two like 2, 4, 8, 16... but the spec doesn't say that, per se.

> other ROMs with bank sizes less than 4k will be affected by this issue in one way or another, but your particular example was especially dramatic, flushing the problem to the surface

Glad to help.  I will submit any other discrepancies I find then!  I'm looking forward to using Gopher2600 for development.  I'm hoping to do some automatic tests, and your emulator looks very promising for that.

**Comment by JetSetIlly** [comment]
> > To be honest, I'm intrigued by the existing extension of e3p. Is that something you've seen before?
> 
> It's one of the extensions Stella accepts for the format (along with e3+ ...which is apparently more widely supported :))

I'll add it to the list.
 
> Glad to help. I will submit any other discrepancies I find then! I'm looking forward to using Gopher2600 for development.

Excellent. I'm currently got my head stuck in the ARM emulation trying to make the cycle counting more accurate but once I'm finished with that I plan to get back to the debugger. 

I'm keen to hear how people use it - it works for me but other people will have different needs.

> I'm hoping to do some automatic tests, and your emulator looks very promising for that.

I assume you've noticed the regression database and playback recording options in that case.
