### ISSUE TITLE
Cropped screen in World's End

### ISSUE THREAD

**Issue by petran79** [JetSetIlly/Gopher2600#31]
![End of the World (Jone Yuan)](https://github.com/JetSetIlly/Gopher2600/assets/8232210/3486b7fd-70a4-4fff-8eee-3a9ab3ee125b)

While other games display fine, this game is heavily cropped even with pixel perfect ratio.
this is how it should look
https://www.retroplace.com/pics/atari2600/titles/194952--world-end.png

When I brought the replay menu, it would appear fine on the screen video, however in-game it refuses to switch to the correct picture

**Comment by JetSetIlly** [comment]
This seems to have been a problem with v0.31.0 of Gopher2600.

v0.32.0 and v0.32.1 have been released recently and the game seems to be okay in those versions.

**Comment by petran79** [comment]
I am using version 0.32.1
Even tried deleting preferences file.

Same issue in Stella both standalone and retroarch. Only Stella 2014 on RA displays it correctly.

**Comment by JetSetIlly** [comment]
Looking at it again, the reason why it's being cropped like that is because the screen type is being detected as NTSC and not PAL. 

There are a couple of ways you can force the use of PAL. In this case however, the best way is to install the `stella.pro` file. This is part of the Stella project so I don't include it in the Gopher2600 binary but you can download it from the Stella github and install it yourself.

I've written a short entry in the project wiki about it:

https://github.com/JetSetIlly/Gopher2600-Docs/wiki/Box-Art-and-stella.pro-file

There are also instructions for installing box art which you might be interested in.


The reason why it worked for me when I looked earlier is of course, because I have the stella.pro file installed already. Apologies for that. I'll make a mental note of that for the future in case anyone has similar problems.



Thanks for the report!

**Comment by petran79** [comment]
Thanks. I'll try the above solution.
